package com.test.model;

import java.util.Date;

public class Academy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_academy.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_academy.aca_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String acaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_academy.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_academy.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String introducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_academy.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_academy.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Academy(Integer id, String acaName, Integer schoolId, String introducation, Date gmtCreate, Date gmtModify) {
        this.id = id;
        this.acaName = acaName;
        this.schoolId = schoolId;
        this.introducation = introducation;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Academy() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_academy.id
     *
     * @return the value of tb_academy.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_academy.id
     *
     * @param id the value for tb_academy.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_academy.aca_name
     *
     * @return the value of tb_academy.aca_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getAcaName() {
        return acaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_academy.aca_name
     *
     * @param acaName the value for tb_academy.aca_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setAcaName(String acaName) {
        this.acaName = acaName == null ? null : acaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_academy.school_id
     *
     * @return the value of tb_academy.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_academy.school_id
     *
     * @param schoolId the value for tb_academy.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_academy.introducation
     *
     * @return the value of tb_academy.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getIntroducation() {
        return introducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_academy.introducation
     *
     * @param introducation the value for tb_academy.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setIntroducation(String introducation) {
        this.introducation = introducation == null ? null : introducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_academy.gmt_create
     *
     * @return the value of tb_academy.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_academy.gmt_create
     *
     * @param gmtCreate the value for tb_academy.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_academy.gmt_modify
     *
     * @return the value of tb_academy.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_academy.gmt_modify
     *
     * @param gmtModify the value for tb_academy.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}