package com.test.model;

import java.util.Date;

public class Fee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_fee.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_fee.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_fee.sum
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_fee.stu_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_fee.pay_or_income
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Short payOrIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_fee.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_fee.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fee
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Fee(Integer id, String content, Integer sum, Integer stuId, Short payOrIncome, Date gmtCreate, Date gmtModify) {
        this.id = id;
        this.content = content;
        this.sum = sum;
        this.stuId = stuId;
        this.payOrIncome = payOrIncome;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fee
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Fee() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_fee.id
     *
     * @return the value of tb_fee.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_fee.id
     *
     * @param id the value for tb_fee.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_fee.content
     *
     * @return the value of tb_fee.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_fee.content
     *
     * @param content the value for tb_fee.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_fee.sum
     *
     * @return the value of tb_fee.sum
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_fee.sum
     *
     * @param sum the value for tb_fee.sum
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_fee.stu_id
     *
     * @return the value of tb_fee.stu_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_fee.stu_id
     *
     * @param stuId the value for tb_fee.stu_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_fee.pay_or_income
     *
     * @return the value of tb_fee.pay_or_income
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Short getPayOrIncome() {
        return payOrIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_fee.pay_or_income
     *
     * @param payOrIncome the value for tb_fee.pay_or_income
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setPayOrIncome(Short payOrIncome) {
        this.payOrIncome = payOrIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_fee.gmt_create
     *
     * @return the value of tb_fee.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_fee.gmt_create
     *
     * @param gmtCreate the value for tb_fee.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_fee.gmt_modify
     *
     * @return the value of tb_fee.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_fee.gmt_modify
     *
     * @param gmtModify the value for tb_fee.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}