package com.test.model;

import java.util.Date;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.gra_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String graName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer academyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.teacher_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String introducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Grade(Integer id, String graName, Integer academyId, Integer teacherId, String introducation, Date gmtCreate, Date gmtModify) {
        this.id = id;
        this.graName = graName;
        this.academyId = academyId;
        this.teacherId = teacherId;
        this.introducation = introducation;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Grade() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.id
     *
     * @return the value of tb_grade.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.id
     *
     * @param id the value for tb_grade.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.gra_name
     *
     * @return the value of tb_grade.gra_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getGraName() {
        return graName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.gra_name
     *
     * @param graName the value for tb_grade.gra_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGraName(String graName) {
        this.graName = graName == null ? null : graName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.academy_id
     *
     * @return the value of tb_grade.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getAcademyId() {
        return academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.academy_id
     *
     * @param academyId the value for tb_grade.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setAcademyId(Integer academyId) {
        this.academyId = academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.teacher_id
     *
     * @return the value of tb_grade.teacher_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.teacher_id
     *
     * @param teacherId the value for tb_grade.teacher_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.introducation
     *
     * @return the value of tb_grade.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getIntroducation() {
        return introducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.introducation
     *
     * @param introducation the value for tb_grade.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setIntroducation(String introducation) {
        this.introducation = introducation == null ? null : introducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.gmt_create
     *
     * @return the value of tb_grade.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.gmt_create
     *
     * @param gmtCreate the value for tb_grade.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade.gmt_modify
     *
     * @return the value of tb_grade.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade.gmt_modify
     *
     * @param gmtModify the value for tb_grade.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}