package com.test.model;

import java.util.Date;

public class GroupContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupcontent.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupcontent.from_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupcontent.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupcontent.state
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupcontent.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupcontent.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_groupcontent.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_groupcontent
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public GroupContent(Integer id, Integer fromId, Integer classId, Short state, Date gmtCreate, Date gmtModify, String content) {
        this.id = id;
        this.fromId = fromId;
        this.classId = classId;
        this.state = state;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_groupcontent
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public GroupContent() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupcontent.id
     *
     * @return the value of tb_groupcontent.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupcontent.id
     *
     * @param id the value for tb_groupcontent.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupcontent.from_id
     *
     * @return the value of tb_groupcontent.from_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupcontent.from_id
     *
     * @param fromId the value for tb_groupcontent.from_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupcontent.class_id
     *
     * @return the value of tb_groupcontent.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupcontent.class_id
     *
     * @param classId the value for tb_groupcontent.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupcontent.state
     *
     * @return the value of tb_groupcontent.state
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupcontent.state
     *
     * @param state the value for tb_groupcontent.state
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupcontent.gmt_create
     *
     * @return the value of tb_groupcontent.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupcontent.gmt_create
     *
     * @param gmtCreate the value for tb_groupcontent.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupcontent.gmt_modify
     *
     * @return the value of tb_groupcontent.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupcontent.gmt_modify
     *
     * @param gmtModify the value for tb_groupcontent.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_groupcontent.content
     *
     * @return the value of tb_groupcontent.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_groupcontent.content
     *
     * @param content the value for tb_groupcontent.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}