package com.test.model;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.topic
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.teacher_or_student
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Short teacherOrStudent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.from_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.state
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_notice.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Notice(Integer id, String topic, String content, Short teacherOrStudent, Integer gradeId, Integer classId, Integer fromId, Short state, Date gmtCreate, Date gmtModify) {
        this.id = id;
        this.topic = topic;
        this.content = content;
        this.teacherOrStudent = teacherOrStudent;
        this.gradeId = gradeId;
        this.classId = classId;
        this.fromId = fromId;
        this.state = state;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Notice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.id
     *
     * @return the value of tb_notice.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.id
     *
     * @param id the value for tb_notice.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.topic
     *
     * @return the value of tb_notice.topic
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.topic
     *
     * @param topic the value for tb_notice.topic
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.content
     *
     * @return the value of tb_notice.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.content
     *
     * @param content the value for tb_notice.content
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.teacher_or_student
     *
     * @return the value of tb_notice.teacher_or_student
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Short getTeacherOrStudent() {
        return teacherOrStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.teacher_or_student
     *
     * @param teacherOrStudent the value for tb_notice.teacher_or_student
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setTeacherOrStudent(Short teacherOrStudent) {
        this.teacherOrStudent = teacherOrStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.grade_id
     *
     * @return the value of tb_notice.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.grade_id
     *
     * @param gradeId the value for tb_notice.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.class_id
     *
     * @return the value of tb_notice.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.class_id
     *
     * @param classId the value for tb_notice.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.from_id
     *
     * @return the value of tb_notice.from_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.from_id
     *
     * @param fromId the value for tb_notice.from_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.state
     *
     * @return the value of tb_notice.state
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.state
     *
     * @param state the value for tb_notice.state
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.gmt_create
     *
     * @return the value of tb_notice.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.gmt_create
     *
     * @param gmtCreate the value for tb_notice.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_notice.gmt_modify
     *
     * @return the value of tb_notice.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_notice.gmt_modify
     *
     * @param gmtModify the value for tb_notice.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}