package com.test.model;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.number
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.pwd
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.student_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.sex
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.birth
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.phone
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.address
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.avator
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String avator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.department
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.email
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.is_commitee
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Short isCommitee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer academyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Student(Integer id, String number, String pwd, String studentName, Short sex, Date birth, String phone, String address, String avator, String department, String email, Short isCommitee, Integer schoolId, Integer academyId, Integer gradeId, Integer classId, Date gmtCreate, Date gmtModify) {
        this.id = id;
        this.number = number;
        this.pwd = pwd;
        this.studentName = studentName;
        this.sex = sex;
        this.birth = birth;
        this.phone = phone;
        this.address = address;
        this.avator = avator;
        this.department = department;
        this.email = email;
        this.isCommitee = isCommitee;
        this.schoolId = schoolId;
        this.academyId = academyId;
        this.gradeId = gradeId;
        this.classId = classId;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Student() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.id
     *
     * @return the value of tb_student.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.id
     *
     * @param id the value for tb_student.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.number
     *
     * @return the value of tb_student.number
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.number
     *
     * @param number the value for tb_student.number
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.pwd
     *
     * @return the value of tb_student.pwd
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.pwd
     *
     * @param pwd the value for tb_student.pwd
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.student_name
     *
     * @return the value of tb_student.student_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.student_name
     *
     * @param studentName the value for tb_student.student_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.sex
     *
     * @return the value of tb_student.sex
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.sex
     *
     * @param sex the value for tb_student.sex
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.birth
     *
     * @return the value of tb_student.birth
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.birth
     *
     * @param birth the value for tb_student.birth
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.phone
     *
     * @return the value of tb_student.phone
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.phone
     *
     * @param phone the value for tb_student.phone
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.address
     *
     * @return the value of tb_student.address
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.address
     *
     * @param address the value for tb_student.address
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.avator
     *
     * @return the value of tb_student.avator
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getAvator() {
        return avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.avator
     *
     * @param avator the value for tb_student.avator
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setAvator(String avator) {
        this.avator = avator == null ? null : avator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.department
     *
     * @return the value of tb_student.department
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.department
     *
     * @param department the value for tb_student.department
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.email
     *
     * @return the value of tb_student.email
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.email
     *
     * @param email the value for tb_student.email
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.is_commitee
     *
     * @return the value of tb_student.is_commitee
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Short getIsCommitee() {
        return isCommitee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.is_commitee
     *
     * @param isCommitee the value for tb_student.is_commitee
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setIsCommitee(Short isCommitee) {
        this.isCommitee = isCommitee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.school_id
     *
     * @return the value of tb_student.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.school_id
     *
     * @param schoolId the value for tb_student.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.academy_id
     *
     * @return the value of tb_student.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getAcademyId() {
        return academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.academy_id
     *
     * @param academyId the value for tb_student.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setAcademyId(Integer academyId) {
        this.academyId = academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.grade_id
     *
     * @return the value of tb_student.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.grade_id
     *
     * @param gradeId the value for tb_student.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.class_id
     *
     * @return the value of tb_student.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.class_id
     *
     * @param classId the value for tb_student.class_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.gmt_create
     *
     * @return the value of tb_student.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.gmt_create
     *
     * @param gmtCreate the value for tb_student.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.gmt_modify
     *
     * @return the value of tb_student.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.gmt_modify
     *
     * @param gmtModify the value for tb_student.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", number='" + number + '\'' +
                ", pwd='" + pwd + '\'' +
                ", studentName='" + studentName + '\'' +
                ", sex=" + sex +
                ", birth=" + birth +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                ", avator='" + avator + '\'' +
                ", department='" + department + '\'' +
                ", email='" + email + '\'' +
                ", isCommitee=" + isCommitee +
                ", schoolId=" + schoolId +
                ", academyId=" + academyId +
                ", gradeId=" + gradeId +
                ", classId=" + classId +
                ", gmtCreate=" + gmtCreate +
                ", gmtModify=" + gmtModify +
                '}';
    }
}