package com.test.model;

import java.util.Date;

public class TbClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.cla_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String claName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String introducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * 班导师
     */
    private String claTeacher;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public TbClass(Integer id, String claName, Integer gradeId, String introducation, Date gmtCreate, Date gmtModify,String claTeacher) {
        this.id = id;
        this.claName = claName;
        this.gradeId = gradeId;
        this.introducation = introducation;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
        this.claTeacher=claTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public TbClass() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.id
     *
     * @return the value of tb_class.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.id
     *
     * @param id the value for tb_class.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.cla_name
     *
     * @return the value of tb_class.cla_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getClaName() {
        return claName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.cla_name
     *
     * @param claName the value for tb_class.cla_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setClaName(String claName) {
        this.claName = claName == null ? null : claName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.grade_id
     *
     * @return the value of tb_class.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.grade_id
     *
     * @param gradeId the value for tb_class.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.introducation
     *
     * @return the value of tb_class.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getIntroducation() {
        return introducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.introducation
     *
     * @param introducation the value for tb_class.introducation
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setIntroducation(String introducation) {
        this.introducation = introducation == null ? null : introducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.gmt_create
     *
     * @return the value of tb_class.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.gmt_create
     *
     * @param gmtCreate the value for tb_class.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.gmt_modify
     *
     * @return the value of tb_class.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.gmt_modify
     *
     * @param gmtModify the value for tb_class.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    public String getClaTeacher() {
        return claTeacher;
    }

    public void setClaTeacher(String claTeacher) {
        this.claTeacher = claTeacher;
    }

    @Override
    public String toString() {
        return "TbClass{" +
                "id=" + id +
                ", claName='" + claName + '\'' +
                ", gradeId=" + gradeId +
                ", introducation='" + introducation + '\'' +
                ", gmtCreate=" + gmtCreate +
                ", gmtModify=" + gmtModify +
                ", claTeacher='" + claTeacher + '\'' +
                '}';
    }
}