package com.test.model;

import java.util.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.emplyee_number
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String employeeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.tea_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.pwd
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.sex
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.birth
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date hireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.phone
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.email
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.avator
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private String avator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer academyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Teacher(Integer id, String employeeNumber, String teaName, String pwd, Short sex, Date hireDate, String phone, String email, String avator, Integer schoolId, Integer academyId, Integer gradeId, Date gmtCreate, Date gmtModify) {
        this.id = id;
        this.employeeNumber = employeeNumber;
        this.teaName = teaName;
        this.pwd = pwd;
        this.sex = sex;
        this.hireDate = hireDate;
        this.phone = phone;
        this.email = email;
        this.avator = avator;
        this.schoolId = schoolId;
        this.academyId = academyId;
        this.gradeId = gradeId;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Teacher() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.id
     *
     * @return the value of tb_teacher.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.id
     *
     * @param id the value for tb_teacher.id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.emplyee_number
     *
     * @return the value of tb_teacher.emplyee_number
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.emplyee_number
     *
     * @param employeeNumber the value for tb_teacher.emplyee_number
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber == null ? null : employeeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.tea_name
     *
     * @return the value of tb_teacher.tea_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.tea_name
     *
     * @param teaName the value for tb_teacher.tea_name
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName == null ? null : teaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.pwd
     *
     * @return the value of tb_teacher.pwd
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.pwd
     *
     * @param pwd the value for tb_teacher.pwd
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.sex
     *
     * @return the value of tb_teacher.sex
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.sex
     *
     * @param sex the value for tb_teacher.sex
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.birth
     *
     * @return the value of tb_teacher.birth
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.birth
     *
     * @param hireDate the value for tb_teacher.birth
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.phone
     *
     * @return the value of tb_teacher.phone
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.phone
     *
     * @param phone the value for tb_teacher.phone
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.email
     *
     * @return the value of tb_teacher.email
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.email
     *
     * @param email the value for tb_teacher.email
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.avator
     *
     * @return the value of tb_teacher.avator
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public String getAvator() {
        return avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.avator
     *
     * @param avator the value for tb_teacher.avator
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setAvator(String avator) {
        this.avator = avator == null ? null : avator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.school_id
     *
     * @return the value of tb_teacher.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.school_id
     *
     * @param schoolId the value for tb_teacher.school_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.academy_id
     *
     * @return the value of tb_teacher.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getAcademyId() {
        return academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.academy_id
     *
     * @param academyId the value for tb_teacher.academy_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setAcademyId(Integer academyId) {
        this.academyId = academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.grade_id
     *
     * @return the value of tb_teacher.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.grade_id
     *
     * @param gradeId the value for tb_teacher.grade_id
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.gmt_create
     *
     * @return the value of tb_teacher.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.gmt_create
     *
     * @param gmtCreate the value for tb_teacher.gmt_create
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.gmt_modify
     *
     * @return the value of tb_teacher.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.gmt_modify
     *
     * @param gmtModify the value for tb_teacher.gmt_modify
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}