package com.test.dao;

import com.test.model.Academy;

import java.util.List;

public interface AcademyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int insert(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int insertSelective(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    Academy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int updateByPrimaryKeySelective(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_academy
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int updateByPrimaryKey(Academy record);

    /**
     * 根据学校的id和学院姓名查找学院
     */
    Academy selectByIdAndName(String name,int id);


    /**
     * 根据学校id查找所有学院
     */
    List<Academy> listBySchoolId(int schoolId);
}