package com.test.dao;

import com.test.model.CourseClass;

import java.util.List;

public interface CourseClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int insert(CourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int insertSelective(CourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    CourseClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int updateByPrimaryKeySelective(CourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated Tue Feb 21 19:58:30 CST 2017
     */
    int updateByPrimaryKey(CourseClass record);

    //根据班级id查询所有课程
    List<CourseClass> listByClassId(int classId);

    //根据课程id查询所有的班级
    List<CourseClass> listByCourseId(int courseId);
}